# Generated by Django 2.2.7 on 2019-12-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(default=1, upload_to=' '),
            preserve_default=False,
        ),
    ]
