# Generated by Django 2.2.7 on 2019-12-06 17:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0002_qrcode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='zone',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='serviceapp.QRZone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='contact',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
