# Generated by Django 2.2.7 on 2019-12-06 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0003_auto_20191206_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceapp.QRZone'),
        ),
    ]
